### ISSUE TITLE
NAs that are word onsets get skipped

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/wordcompare#1]
The script _should not_ include "NA" in the output lists, but it _should_ include items that just _start_ with NA, e.g. nachos. These are currently being skipped over; video files 07_08 can be used as test files for whether the fix works

**Comment by andreiamatuni** [comment]
files for 07_08 aren't in the test folder, could you please upload those?

**Comment by andreiamatuni** [comment]
looks like this may be due to the coding of the data, not the program itself. Possibly due to excel autocompleting "nacho" as "NA" for basic_level. Closing issue.
